# Generated by Django 5.2.3 on 2025-07-14 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='funcao')),
            ],
            options={
                'verbose_name': 'funcao',
                'verbose_name_plural': 'funcoes',
            },
        ),
        migrations.CreateModel(
            name='pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Pergunta')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
                ('dat_cria', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
            ],
            options={
                'verbose_name': 'pergunta',
                'verbose_name_plural': 'perguntas',
            },
        ),
        migrations.CreateModel(
            name='questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Questionario_Now()', max_length=100, verbose_name='Nome do questionario')),
                ('freq', models.CharField(max_length=50)),
                ('dat_cria', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('ativo', models.BooleanField(verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'questionario',
                'verbose_name_plural': 'questionarios',
            },
        ),
        migrations.CreateModel(
            name='tipoPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo de Pergunta')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'tipopergunta',
                'verbose_name_plural': 'tipoperguntas',
            },
        ),
        migrations.CreateModel(
            name='questionarioPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pergunta_Now()', max_length=100, verbose_name='Nome da Pergunta')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pergunta', verbose_name='Pergunta')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questionario', verbose_name='Questionario')),
            ],
            options={
                'verbose_name': 'questionariopergunta',
                'verbose_name_plural': 'questionarioperguntas',
            },
        ),
        migrations.AddField(
            model_name='pergunta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipopergunta', verbose_name='Tipo de Pergunta'),
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='nome')),
                ('contato', models.CharField(max_length=50, verbose_name='contato')),
                ('dat_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcao', verbose_name='funcao')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Resposta_Now()', max_length=100, verbose_name='Nome da Resposta')),
                ('resposta', models.CharField(max_length=100, verbose_name='Resposta')),
                ('dat_cria', models.DateTimeField(auto_now_add=True, verbose_name='data de cadastro')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pergunta', verbose_name='Pergunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'resposta',
                'verbose_name_plural': 'respostas',
            },
        ),
    ]
