# Generated by Django 5.2.3 on 2025-07-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='123456', max_length=50, verbose_name='senha'),
        ),
    ]
