# Generated by Django 5.2.3 on 2025-07-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do questionario'),
        ),
        migrations.AlterField(
            model_name='questionariopergunta',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da Pergunta'),
        ),
    ]
