# Generated by Django 5.2.3 on 2025-07-14 11:12

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_questionario_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='dat_cria',
            field=models.DateTimeField(default=django.db.models.functions.datetime.Now(), verbose_name='data de cadastro'),
        ),
    ]
