# Generated by Django 5.2.3 on 2025-07-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_pergunta_dat_cria_alter_questionario_dat_cria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='dat_cria',
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='dat_cria',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='dat_cria',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='dat_cadastro',
        ),
        migrations.AlterField(
            model_name='resposta',
            name='nome',
            field=models.CharField(default='Resposta_1752492220.187693', max_length=100, verbose_name='Nome da Resposta'),
        ),
    ]
