# Generated by Django 5.2.3 on 2025-07-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_pergunta_dat_cria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='nome',
            field=models.CharField(default='Resposta_1752492287.167571', max_length=100, verbose_name='Nome da Resposta'),
        ),
    ]
