# Generated by Django 5.2.3 on 2025-07-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_resposta_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='nome',
            field=models.CharField(default='Resposta_1752492291.764357', max_length=100, verbose_name='Nome da Resposta'),
        ),
    ]
