# Generated by Django 5.2.3 on 2025-07-14 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_resposta_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='dat_cria',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='dat_cria',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='dat_cria',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='dat_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='data de cadastro'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='nome',
            field=models.CharField(default='Resposta_1752492407.418282', max_length=100, verbose_name='Nome da Resposta'),
        ),
    ]
