# Generated by Django 5.2.3 on 2025-07-14 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_pergunta_dat_cria_questionario_dat_cria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='freqQuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do questionario')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'freqquestionario',
                'verbose_name_plural': 'freqquestionarios',
            },
        ),
        migrations.AlterField(
            model_name='resposta',
            name='nome',
            field=models.CharField(default='Resposta_1752492767.972025', max_length=100, verbose_name='Nome da Resposta'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='freq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.freqquestionario', verbose_name='Frequencia do Questionario'),
        ),
    ]
