# Generated by Django 5.2.3 on 2025-07-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_freqquestionario_alter_resposta_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freqquestionario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='frequencia'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='nome',
            field=models.CharField(default='Resposta_1752492848.375168', max_length=100, verbose_name='Nome da Resposta'),
        ),
    ]
