# Generated by Django 5.2.3 on 2025-07-14 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_freqquestionario_nome_alter_resposta_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionariopergunta',
            name='name',
            field=models.CharField(default='Pergunta_1752494231.852623', max_length=100, verbose_name='Nome da Pergunta'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='nome',
            field=models.CharField(default='Resposta_1752494231.851623', max_length=100, verbose_name='Nome da Resposta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='funcao',
            field=models.ForeignKey(default='user', on_delete=django.db.models.deletion.CASCADE, to='app.funcao', verbose_name='funcao'),
        ),
    ]
